[versions]
byteBuddy = "1.15.7"
checkstyle = "10.18.2"
junit5 = "5.11.3"
jmh = "1.37"
gradle = "8.10.2"

[libraries]
junit4 = { group = "junit", name = "junit", version = "4.13.2" }
guava = { group = "com.google.guava", name = "guava-testlib", version = "33.3.1-jre" }
mockito = { group = "org.mockito", name = "mockito-core", version = "5.14.2" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version = "3.0" }
findbugs = { group = "com.google.code.findbugs", name = "findbugs-annotations", version = "3.0.1" }
byteBuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byteBuddy" }
byteBuddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "byteBuddy" }
byteBuddy-gradle-plugin = { group = "net.bytebuddy", name = "byte-buddy-gradle-plugin", version.ref = "byteBuddy" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
jcstress-core = { group = "org.openjdk.jcstress", name = "jcstress-core", version = "0.16" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
bnd = { id = "biz.aQute.bnd.builder", version = "7.0.0" }
shadow = { id = "com.gradleup.shadow", version = "8.3.4" }
